#!/usr/bin/env python
"""Build and register the CoT-control DPO datasets used by LLaMA-Factory."""

from __future__ import annotations

import argparse
import collections
import json
import random
import re
from pathlib import Path
from typing import Callable


THINK_RE = re.compile(r"^\s*<think>\s*(.*?)\s*</think>\s*(.*)\s*$", re.DOTALL)
DISCLAIMER = "THIS THOUGHT PROCESS WAS GENERATED BY AI"
COLUMNS = {
    "prompt": "instruction",
    "query": "input",
    "chosen": "chosen",
    "rejected": "rejected",
}

VARIANTS: dict[str, tuple[str, Callable[[str], str]]] = {
    "all_caps": (
        "Think step-by-step. Your reasoning must be in English and in ALL CAPITAL "
        "LETTERS. The final answer may use normal capitalization.",
        str.upper,
    ),
    "no_commas": (
        "Think step-by-step. Your reasoning must not contain commas. The final "
        "answer may use commas naturally.",
        lambda text: text.replace(",", ""),
    ),
    "disclaimer_at_end": (
        f"Think step-by-step. End your reasoning with the exact disclaimer: "
        f"{DISCLAIMER}. Put it immediately before </think>.",
        lambda text: f"{text.rstrip()}\n\n{DISCLAIMER}",
    ),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/multilingual_thinking_qwen3_4b_cots.json"),
    )
    parser.add_argument("--output-dir", type=Path, default=Path("data"))
    parser.add_argument("--eval-size", type=int, default=100)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def source_reasoning(sample: dict) -> str:
    reasoning = sample.get("thinking_content")
    if reasoning is None:
        reasoning = sample["reasoning_content"]
    match = THINK_RE.match(reasoning)
    return (match.group(1) if match else reasoning).strip()


def response(reasoning: str, answer: str) -> str:
    return f"<think>\n{reasoning.strip()}\n</think>\n\n{answer.strip()}"


def build_rows(source: list[dict], instruction: str, transform: Callable[[str], str]) -> list[dict]:
    rows = []
    for sample in source:
        reasoning = source_reasoning(sample)
        answer = sample["final_answer"]
        rows.append(
            {
                "instruction": instruction,
                "input": sample["question"].strip(),
                "chosen": response(transform(reasoning), answer),
                "rejected": response(reasoning, answer),
            }
        )
    return rows


def split_rows(rows: list[dict], eval_size: int, seed: int) -> tuple[list[dict], list[dict]]:
    groups: dict[str, list[dict]] = collections.defaultdict(list)
    for row in rows:
        groups[row["input"]].append(row)
    grouped = list(groups.values())
    random.Random(seed).shuffle(grouped)

    eval_groups: list[list[dict]] = []
    eval_count = 0
    while grouped and eval_count < eval_size:
        group = grouped.pop()
        eval_groups.append(group)
        eval_count += len(group)

    train = [row for group in grouped for row in group]
    evaluation = [row for group in eval_groups for row in group]
    random.Random(seed + 1).shuffle(train)
    random.Random(seed + 2).shuffle(evaluation)
    return train, evaluation


def split_response(text: str) -> tuple[str, str]:
    match = THINK_RE.match(text)
    if not match:
        raise ValueError("response does not contain one leading <think> block")
    return match.group(1).strip(), match.group(2).strip()


def validate(variant: str, rows: list[dict]) -> None:
    required = {"instruction", "input", "chosen", "rejected"}
    for index, row in enumerate(rows):
        if set(row) != required or not all(isinstance(row[key], str) for key in required):
            raise ValueError(f"{variant}[{index}] has an invalid LLaMA-Factory schema")
        chosen_reasoning, chosen_answer = split_response(row["chosen"])
        rejected_reasoning, rejected_answer = split_response(row["rejected"])
        if chosen_answer != rejected_answer:
            raise ValueError(f"{variant}[{index}] changes the final answer")
        if variant == "all_caps" and chosen_reasoning != rejected_reasoning.upper():
            raise ValueError(f"{variant}[{index}] is not a case-only preference pair")
        if variant == "no_commas" and chosen_reasoning != rejected_reasoning.replace(",", ""):
            raise ValueError(f"{variant}[{index}] is not a comma-removal preference pair")
        if variant == "disclaimer_at_end":
            expected = f"{rejected_reasoning.rstrip()}\n\n{DISCLAIMER}"
            if chosen_reasoning != expected:
                raise ValueError(f"{variant}[{index}] does not end with the disclaimer")


def validate_external(name: str, rows: list[dict]) -> None:
    """Validate prebuilt preference files such as the multilingual controls."""
    required = {"instruction", "input", "chosen", "rejected"}
    if not rows:
        raise ValueError(f"{name} is empty")
    for index, row in enumerate(rows):
        if set(row) != required or not all(isinstance(row[key], str) for key in required):
            raise ValueError(f"{name}[{index}] has an invalid LLaMA-Factory schema")
        _, chosen_answer = split_response(row["chosen"])
        _, rejected_answer = split_response(row["rejected"])
        if chosen_answer != rejected_answer:
            raise ValueError(f"{name}[{index}] changes the final answer")


def main() -> None:
    args = parse_args()
    source = json.loads(args.input.read_text(encoding="utf-8"))
    if not isinstance(source, list) or not source:
        raise ValueError("input must be a non-empty JSON array")
    if not 0 < args.eval_size < len(source):
        raise ValueError("eval-size must be between zero and the source row count")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    registry = {}
    for variant, (instruction, transform) in VARIANTS.items():
        rows = build_rows(source, instruction, transform)
        validate(variant, rows)
        train, evaluation = split_rows(rows, args.eval_size, args.seed)
        for split, split_rows_ in (("train", train), ("eval", evaluation)):
            filename = f"{variant}_dpo_{split}.json"
            (args.output_dir / filename).write_text(
                json.dumps(split_rows_, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            registry[f"{variant}_dpo_{split}"] = {
                "file_name": filename,
                "ranking": True,
                "columns": COLUMNS,
            }
        print(f"{variant}: {len(train)} train, {len(evaluation)} eval")

    # Multilingual controls are built separately because their preferred
    # reasoning is translated. Preserve, validate, and register every language
    # split that is present alongside the generated datasets.
    multilingual_files = sorted(args.output_dir.glob("multilingual_*_dpo_*.json"))
    for path in multilingual_files:
        name = path.stem
        rows = json.loads(path.read_text(encoding="utf-8"))
        validate_external(name, rows)
        registry[name] = {
            "file_name": path.name,
            "ranking": True,
            "columns": COLUMNS,
        }
        print(f"{name}: {len(rows)} rows")

    (args.output_dir / "dataset_info.json").write_text(
        json.dumps(registry, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Registered {len(registry)} datasets in {args.output_dir / 'dataset_info.json'}")


if __name__ == "__main__":
    main()
